# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sukran/D/Relimetrics/ParallelJobsManager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sukran/D/Relimetrics/ParallelJobsManager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sukran/D/Relimetrics/ParallelJobsManager/CMakeFiles /media/sukran/D/Relimetrics/ParallelJobsManager/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sukran/D/Relimetrics/ParallelJobsManager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TaskManager

# Build rule for target.
TaskManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TaskManager
.PHONY : TaskManager

# fast build rule for target.
TaskManager/fast:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/build
.PHONY : TaskManager/fast

EvenCounter.o: EvenCounter.cpp.o

.PHONY : EvenCounter.o

# target to build an object file
EvenCounter.cpp.o:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/EvenCounter.cpp.o
.PHONY : EvenCounter.cpp.o

EvenCounter.i: EvenCounter.cpp.i

.PHONY : EvenCounter.i

# target to preprocess a source file
EvenCounter.cpp.i:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/EvenCounter.cpp.i
.PHONY : EvenCounter.cpp.i

EvenCounter.s: EvenCounter.cpp.s

.PHONY : EvenCounter.s

# target to generate assembly for a file
EvenCounter.cpp.s:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/EvenCounter.cpp.s
.PHONY : EvenCounter.cpp.s

OddCounter.o: OddCounter.cpp.o

.PHONY : OddCounter.o

# target to build an object file
OddCounter.cpp.o:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/OddCounter.cpp.o
.PHONY : OddCounter.cpp.o

OddCounter.i: OddCounter.cpp.i

.PHONY : OddCounter.i

# target to preprocess a source file
OddCounter.cpp.i:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/OddCounter.cpp.i
.PHONY : OddCounter.cpp.i

OddCounter.s: OddCounter.cpp.s

.PHONY : OddCounter.s

# target to generate assembly for a file
OddCounter.cpp.s:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/OddCounter.cpp.s
.PHONY : OddCounter.cpp.s

Task.o: Task.cpp.o

.PHONY : Task.o

# target to build an object file
Task.cpp.o:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/Task.cpp.o
.PHONY : Task.cpp.o

Task.i: Task.cpp.i

.PHONY : Task.i

# target to preprocess a source file
Task.cpp.i:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/Task.cpp.i
.PHONY : Task.cpp.i

Task.s: Task.cpp.s

.PHONY : Task.s

# target to generate assembly for a file
Task.cpp.s:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/Task.cpp.s
.PHONY : Task.cpp.s

TaskManager.o: TaskManager.cpp.o

.PHONY : TaskManager.o

# target to build an object file
TaskManager.cpp.o:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/TaskManager.cpp.o
.PHONY : TaskManager.cpp.o

TaskManager.i: TaskManager.cpp.i

.PHONY : TaskManager.i

# target to preprocess a source file
TaskManager.cpp.i:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/TaskManager.cpp.i
.PHONY : TaskManager.cpp.i

TaskManager.s: TaskManager.cpp.s

.PHONY : TaskManager.s

# target to generate assembly for a file
TaskManager.cpp.s:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/TaskManager.cpp.s
.PHONY : TaskManager.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TaskManager.dir/build.make CMakeFiles/TaskManager.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TaskManager"
	@echo "... EvenCounter.o"
	@echo "... EvenCounter.i"
	@echo "... EvenCounter.s"
	@echo "... OddCounter.o"
	@echo "... OddCounter.i"
	@echo "... OddCounter.s"
	@echo "... Task.o"
	@echo "... Task.i"
	@echo "... Task.s"
	@echo "... TaskManager.o"
	@echo "... TaskManager.i"
	@echo "... TaskManager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

